// data.js — Yerleşik (hazır) kategoriler.
// Her kelime bir çift olarak yazılır: ['Kelime', 'ipucu'].
// İpucu, gizli kelimeyi ÇAĞRIŞTIRAN kısa bir kelime/ifadedir (kelimenin kendisi
// ya da aynı kategoriden başka bir kelime DEĞİL). İmposter'a bu ipucu gösterilir.
// Kendi kategorilerini "Kategoriler" ekranından ekleyebilirsin; orada da
// "Kelime | ipucu" biçimini kullanabilirsin (ipucu opsiyoneldir).

const BUILTIN_CATEGORIES = [
  {
    id: 'b_hayvanlar',
    name: '🐾 Hayvanlar',
    words: [
      ['Aslan', 'yele'], ['Kaplan', 'çizgi'], ['Fil', 'hortum'], ['Zürafa', 'uzun boyun'],
      ['Zebra', 'çizgili'], ['Panda', 'bambu'], ['Kanguru', 'kese'], ['Timsah', 'bataklık'],
      ['Penguen', 'frak'], ['Baykuş', 'gece'], ['Kartal', 'zirve'], ['Yunus', 'zeki'],
      ['Köpekbalığı', 'yüzgeç'], ['Ahtapot', 'sekiz kol'], ['Yılan', 'zehir'], ['Kaplumbağa', 'kabuk'],
      ['Tavşan', 'havuç'], ['Sincap', 'fındık'], ['Kirpi', 'diken'], ['Yarasa', 'baş aşağı'],
      ['Deve', 'çöl'], ['Su aygırı', 'nehir'], ['Gorilla', 'göğüs döven'], ['Şempanze', 'taklit'],
      ['Kurt', 'uluma'], ['Tilki', 'kurnaz'], ['Ayı', 'kış uykusu'], ['Geyik', 'boynuz'],
      ['Karınca', 'koloni'], ['Arı', 'kovan'],
    ],
  },
  {
    id: 'b_meyve_sebze',
    name: '🍎 Meyve & Sebze',
    words: [
      ['Elma', 'Newton'], ['Armut', 'damla şekli'], ['Muz', 'maymun'], ['Çilek', 'reçel'],
      ['Karpuz', 'yaz'], ['Kavun', 'sarı iç'], ['Üzüm', 'salkım'], ['Portakal', 'C vitamini'],
      ['Mandalina', 'kolay soyulur'], ['Kiraz', 'çift sap'], ['Vişne', 'ekşi'], ['Şeftali', 'tüylü'],
      ['Kayısı', 'Malatya'], ['Nar', 'tane tane'], ['İncir', 'Ege'], ['Kivi', 'yeşil iç'],
      ['Ananas', 'tropik'], ['Avokado', 'yağlı'], ['Domates', 'salça'], ['Salatalık', 'turşu'],
      ['Patates', 'kızartma'], ['Soğan', 'ağlatır'], ['Havuç', 'tavşan'], ['Biber', 'acı'],
      ['Patlıcan', 'mor'], ['Kabak', 'mücver'], ['Ispanak', 'Temel Reis'], ['Marul', 'salata'],
      ['Mısır', 'patlamış'], ['Sarımsak', 'vampir'],
    ],
  },
  {
    id: 'b_ulkeler',
    name: '🌍 Ülkeler',
    words: [
      ['Türkiye', 'iki kıta'], ['Almanya', 'otoban'], ['Fransa', 'Eyfel'], ['İtalya', 'çizme'],
      ['İspanya', 'boğa'], ['İngiltere', 'kraliçe'], ['Hollanda', 'yel değirmeni'], ['Yunanistan', 'mitoloji'],
      ['Rusya', 'votka'], ['Çin', 'set'], ['Japonya', 'sakura'], ['Güney Kore', 'kpop'],
      ['Hindistan', 'köri'], ['Brezilya', 'samba'], ['Arjantin', 'tango'], ['Meksika', 'sombrero'],
      ['Kanada', 'akçaağaç'], ['Amerika', 'kovboy'], ['Mısır', 'piramit'], ['Fas', 'çarşı'],
      ['Nijerya', 'Nollywood'], ['Avustralya', 'kanguru'], ['İsveç', 'IKEA'], ['Norveç', 'fiyort'],
      ['Portekiz', 'Ronaldo'], ['Polonya', 'Chopin'], ['İsviçre', 'saat'], ['Belçika', 'çikolata'],
    ],
  },
  {
    id: 'b_sehirler',
    name: '🏙️ Türkiye Şehirleri',
    words: [
      ['İstanbul', 'boğaz köprüsü'], ['Ankara', 'başkent'], ['İzmir', 'saat kulesi'], ['Bursa', 'İskender'],
      ['Antalya', 'turist'], ['Adana', 'kebap'], ['Konya', 'Mevlana'], ['Gaziantep', 'baklava'],
      ['Trabzon', 'hamsi'], ['Samsun', '19 Mayıs'], ['Eskişehir', 'öğrenci'], ['Kayseri', 'pastırma'],
      ['Mersin', 'tantuni'], ['Diyarbakır', 'surlar'], ['Erzurum', 'dondurucu soğuk'], ['Van', 'kedi'],
      ['Muğla', 'Bodrum'], ['Aydın', 'incir'], ['Denizli', 'horoz'], ['Sakarya', 'meydan savaşı'],
      ['Malatya', 'kayısı'], ['Rize', 'çay'], ['Sivas', 'kangal'], ['Çanakkale', 'geçilmez'],
      ['Balıkesir', 'zeytin'], ['Kocaeli', 'sanayi'], ['Şanlıurfa', 'balıklı göl'], ['Hatay', 'künefe'],
      ['Mardin', 'taş evler'], ['Bolu', 'aşçı'],
    ],
  },
  {
    id: 'b_meslekler',
    name: '👔 Meslekler',
    words: [
      ['Doktor', 'önlük'], ['Öğretmen', 'tebeşir'], ['Mühendis', 'proje'], ['Avukat', 'cübbe'],
      ['Polis', 'rozet'], ['İtfaiyeci', 'yangın'], ['Aşçı', 'kepçe'], ['Garson', 'tepsi'],
      ['Berber', 'makas'], ['Terzi', 'dikiş'], ['Marangoz', 'testere'], ['Elektrikçi', 'kablo'],
      ['Pilot', 'kokpit'], ['Hostes', 'ikram'], ['Kaptan', 'dümen'], ['Şoför', 'direksiyon'],
      ['Hemşire', 'iğne'], ['Eczacı', 'reçete'], ['Diş hekimi', 'matkap'], ['Mimar', 'çizim'],
      ['Ressam', 'fırça'], ['Müzisyen', 'nota'], ['Oyuncu', 'Oscar'], ['Yazar', 'roman'],
      ['Gazeteci', 'mikrofon'], ['Çiftçi', 'traktör'], ['Balıkçı', 'olta'], ['Kasap', 'satır'],
      ['Fırıncı', 'ekmek'], ['Veteriner', 'pati'],
    ],
  },
  {
    id: 'b_filmler',
    name: '🎬 Ünlü Filmler',
    words: [
      ['Titanik', 'buzdağı'], ['Avatar', 'mavi tenli'], ['Yüzüklerin Efendisi', 'yüzük'],
      ['Harry Potter', 'asa'], ['Yıldız Savaşları', 'ışın kılıcı'], ['Matrix', 'kırmızı hap'],
      ['Jurassic Park', 'dinozor'], ['Aslan Kral', 'Simba'], ['Buz Devri', 'mamut'], ['Şrek', 'yeşil dev'],
      ['Karayip Korsanları', 'Sparrow'], ['Örümcek Adam', 'ağ'], ['Batman', 'Gotham'], ['Süpermen', 'pelerin'],
      ['İyi Kötü Çirkin', 'düello'], ['Esaretin Bedeli', 'hapishane'], ['Baba', 'mafya'], ['Forrest Gump', 'koşu'],
      ['Interstellar', 'kara delik'], ['Başlangıç', 'rüya'], ['Joker', 'palyaço'], ['Gladyatör', 'arena'],
      ['Terminatör', 'robot'], ['Rocky', 'boks'], ['Rambo', 'komando'],
    ],
  },
  {
    id: 'b_spor',
    name: '⚽ Spor Dalları',
    words: [
      ['Futbol', 'gol'], ['Basketbol', 'pota'], ['Voleybol', 'file'], ['Tenis', 'kort'],
      ['Yüzme', 'kulaç'], ['Boks', 'yumruk'], ['Güreş', 'kispet'], ['Karate', 'kuşak'],
      ['Judo', 'kimono'], ['Tekvando', 'tekme'], ['Halter', 'ağırlık'], ['Atletizm', 'pist'],
      ['Bisiklet', 'pedal'], ['Kayak', 'kar'], ['Buz pateni', 'piruet'], ['Golf', 'çukur'],
      ['Hokey', 'disk'], ['Beyzbol', 'sopa'], ['Rugby', 'oval top'], ['Masa tenisi', 'pinpon'],
      ['Badminton', 'tüylü top'], ['Okçuluk', 'yay'], ['Eskrim', 'maske'], ['Binicilik', 'eyer'],
      ['Dalış', 'oksijen'], ['Sörf', 'dalga'], ['Kürek', 'tekne'], ['Hentbol', 'el'],
    ],
  },
  {
    id: 'b_ev_esya',
    name: '🛋️ Ev Eşyaları',
    words: [
      ['Koltuk', 'oturma'], ['Masa', 'dört ayak'], ['Sandalye', 'arkalık'], ['Yatak', 'uyku'],
      ['Dolap', 'raf'], ['Buzdolabı', 'soğuk'], ['Fırın', 'pişirme'], ['Çamaşır makinesi', 'deterjan'],
      ['Bulaşık makinesi', 'tabaklar'], ['Televizyon', 'ekran'], ['Halı', 'desen'], ['Perde', 'pencere'],
      ['Ayna', 'yansıma'], ['Lamba', 'abajur'], ['Vantilatör', 'serinlik'], ['Ütü', 'buruşuk'],
      ['Süpürge', 'toz'], ['Tencere', 'kaynatma'], ['Tava', 'kızartma'], ['Bardak', 'içme'],
      ['Tabak', 'yuvarlak'], ['Çatal', 'sivri'], ['Kaşık', 'çorba'], ['Bıçak', 'keskin'],
      ['Yastık', 'baş koyma'], ['Battaniye', 'örtünme'], ['Saat', 'akrep yelkovan'], ['Klima', 'serinletme'],
    ],
  },
  {
    id: 'b_yiyecek',
    name: '🍔 Yiyecek & İçecek',
    words: [
      ['Pizza', 'dilim'], ['Hamburger', 'ekmek arası'], ['Döner', 'şiş'], ['Lahmacun', 'ince hamur'],
      ['Pide', 'Ramazan'], ['Köfte', 'kıyma'], ['Kebap', 'mangal'], ['Mantı', 'yoğurt'],
      ['Börek', 'yufka'], ['Simit', 'susam'], ['Baklava', 'şerbet'], ['Künefe', 'tel peynir'],
      ['Dondurma', 'Maraş'], ['Çikolata', 'kakao'], ['Kek', 'doğum günü'], ['Pasta', 'mum'],
      ['Makarna', 'sos'], ['Pilav', 'pirinç'], ['Çorba', 'kaşık'], ['Salata', 'yeşillik'],
      ['Menemen', 'yumurta'], ['Omlet', 'çırpma'], ['Çay', 'demlik'], ['Kahve', 'kafein'],
      ['Ayran', 'tuzlu'], ['Limonata', 'limon'], ['Kola', 'gazlı'], ['Meyve suyu', 'pipet'],
    ],
  },
  {
    id: 'b_kahraman',
    name: '🦸 Süper Kahramanlar',
    words: [
      ['Örümcek Adam', 'ağ atan'], ['Demir Adam', 'zırh'], ['Kaptan Amerika', 'kalkan'], ['Thor', 'çekiç'],
      ['Hulk', 'öfke'], ['Batman', 'yarasa'], ['Süpermen', 'uçan'], ['Wonder Woman', 'kement'],
      ['Flash', 'hız'], ['Aquaman', 'Atlantis'], ['Kara Panter', 'Wakanda'], ['Doktor Strange', 'portal'],
      ['Ant-Man', 'küçülme'], ['Wolverine', 'pençe'], ['Deadpool', 'laf ebesi'], ['Green Lantern', 'fener'],
      ['Yeşil Ok', 'ok'], ['Kara Dul', 'casus'], ['Şazam', 'çocuk'], ['Venom', 'simbiyot'],
      ['Hawkeye', 'nişancı'], ['Vizyon', 'android'], ['Scarlet Witch', 'kızıl'], ['Star-Lord', 'walkman'],
    ],
  },
  {
    id: 'b_muzik',
    name: '🎸 Müzik & Çalgılar',
    words: [
      ['Gitar', 'akor'], ['Piyano', 'siyah beyaz tuş'], ['Keman', 'çene'], ['Davul', 'ritim'],
      ['Flüt', 'üfleme'], ['Trompet', 'bakır'], ['Saksafon', 'caz'], ['Bağlama', 'saz'],
      ['Ud', 'mızrap'], ['Kanun', 'diz üstü'], ['Ney', 'kamış'], ['Darbuka', 'deri'],
      ['Zurna', 'düğün'], ['Klarnet', 'roman havası'], ['Akordeon', 'körük'], ['Arp', 'melek'],
      ['Çello', 'oturarak'], ['Kontrbas', 'dev gövde'], ['Trombon', 'sürgü'], ['Org', 'kilise'],
      ['Mandolin', 'İtalyan'], ['Ksilofon', 'çubuk'], ['Zil', 'çınlama'], ['Tef', 'çıngırak'],
    ],
  },
  {
    id: 'b_diziler',
    name: '📺 Türk Dizileri',
    words: [
      ['Kurtlar Vadisi', 'Polat'], ['Ezel', 'intikam'], ['Aşk-ı Memnu', 'yasak aşk'],
      ['Muhteşem Yüzyıl', 'Hürrem'], ['Diriliş Ertuğrul', 'Kayı boyu'], ['Çukur', 'mahalle'],
      ['Leyla ile Mecnun', 'Erdal Bakkal'], ['Avrupa Yakası', 'Nişantaşı'],
      ['Çocuklar Duymasın', 'Haluk'], ['Seksenler', 'nostalji'], ['Arka Sokaklar', 'polis ekibi'],
      ['Kara Sevda', 'imkânsız aşk'], ['Kuruluş Osman', 'beylik'], ['Gibi', 'absürt ikili'],
      ['Behzat Ç.', 'Ankara'], ['Yaprak Dökümü', 'Ali Rıza Bey'], ['Kuzey Güney', 'iki kardeş'],
      ['Fatmagül', 'ne suçu vardı'], ['Aşk Yeniden', 'uçakta tanışma'], ['Yalı Çapkını', 'damat'],
    ],
  },
  {
    id: 'b_sarkicilar',
    name: '🎤 Şarkıcılar',
    words: [
      ['Tarkan', 'megastar'], ['Sezen Aksu', 'minik serçe'], ['Barış Manço', 'uzun saç'],
      ['Ajda Pekkan', 'süperstar'], ['İbrahim Tatlıses', 'Urfa'], ['Müslüm Gürses', 'plak babası'],
      ['Zeki Müren', 'sanat güneşi'], ['Orhan Gencebay', 'arabesk'], ['Neşet Ertaş', 'bozkırın tezenesi'],
      ['Cem Karaca', 'Anadolu rock'], ['Ahmet Kaya', 'gitar'], ['Sertab Erener', 'Eurovision'],
      ['MFÖ', 'üçlü grup'], ['Teoman', 'melankoli'], ['Sıla', 'İzmir'], ['Mabel Matiz', 'masalcı'],
      ['Edis', 'pop prensi'], ['Hadise', 'düm tek tek'], ['Kenan Doğulu', 'shake it up'],
      ['Aleyna Tilki', 'genç fenomen'],
    ],
  },
  {
    id: 'b_oyunlar',
    name: '🎮 Video Oyunları',
    words: [
      ['Minecraft', 'küp dünya'], ['Super Mario', 'mantar'], ['Tetris', 'düşen bloklar'],
      ['GTA', 'suç şehri'], ['PUBG', 'son hayatta kalan'], ['Fortnite', 'dans hareketi'],
      ['Among Us', 'şüpheli mürettebat'], ['Candy Crush', 'şeker patlatma'], ['Angry Birds', 'sapan'],
      ['Subway Surfers', 'tren rayları'], ['Pac-Man', 'hayalet yiyen'], ['Yılan', 'eski Nokia'],
      ['FIFA', 'sanal maç'], ['Counter-Strike', 'bomba kurma'], ['League of Legends', 'koridor savaşı'],
      ['The Sims', 'sanal hayat'], ['Zelda', 'efsane kılıç'], ['God of War', 'Kratos'],
      ['Red Dead', 'kovboy'], ['Witcher', 'canavar avcısı'],
    ],
  },
  {
    id: 'b_markalar',
    name: '🏷️ Markalar',
    words: [
      ['Nike', 'swoosh'], ['Adidas', 'üç çizgi'], ['Apple', 'ısırılmış meyve'],
      ['Samsung', 'Koreli dev'], ['Coca-Cola', 'gizli formül'], ['Pepsi', 'mavi kutu'],
      ["McDonald's", 'sarı M'], ['Starbucks', 'deniz kızı'], ['Mercedes', 'üç köşeli yıldız'],
      ['Ferrari', 'şahlanan at'], ['Lamborghini', 'boğa amblemi'], ['LEGO', 'plastik tuğla'],
      ['IKEA', 'alyan anahtarı'], ['Google', 'arama motoru'], ['YouTube', 'kırmızı oynat tuşu'],
      ['Instagram', 'filtreli fotoğraf'], ['Netflix', 'dizi maratonu'], ['Türk Hava Yolları', 'uçan bayrak'],
      ['Arçelik', 'robot maskot'], ['Ülker', 'çikolata devi'], ['BİM', 'ucuz market'],
      ['Migros', 'kanguru logosu'],
    ],
  },
  {
    id: 'b_vucut',
    name: '🖐️ Vücut Bölümleri',
    words: [
      ['Baş', 'düşünme'], ['Saç', 'tarak'], ['Göz', 'gözlük'], ['Kulak', 'küpe'],
      ['Burun', 'koku'], ['Ağız', 'konuşma'], ['Dil', 'tat'], ['Diş', 'fırça'],
      ['Boyun', 'kravat'], ['Omuz', 'apolet'], ['Kol', 'sarılma'], ['Dirsek', 'bükülme'],
      ['El', 'tokalaşma'], ['Parmak', 'iz'], ['Tırnak', 'oje'], ['Göğüs', 'kalp'],
      ['Karın', 'göbek'], ['Sırt', 'yük'], ['Bel', 'kemer'], ['Bacak', 'pantolon'],
      ['Diz', 'çökme'], ['Ayak', 'ayakkabı'], ['Topuk', 'Aşil'], ['Kaş', 'kavis'],
      ['Kirpik', 'maskara'], ['Yanak', 'öpücük'], ['Çene', 'sakal'], ['Alın', 'ter'],
    ],
  },
];
