// data.js — Yerleşik (hazır) kategoriler.
// Her kelime bir çift olarak yazılır: ['Kelime', 'ipucu'].
// İpuçları TEK KELİMEDİR ve etrafından dolaşır: doğrudan eş anlam / birebir
// eşleşme değil (Kanun → yasa OLMAZ), bir adım öteden çağrışım
// (Timsah → gözyaşı, Zebra → geçit, Aslan → burç, Kanun → madde gibi).
// Kendi kategorilerinde "Kelime | ipucu" biçimini kullanabilirsin (opsiyonel).

const BUILTIN_CATEGORIES = [
  {
    id: 'b_hayvanlar',
    name: '🐾 Hayvanlar',
    words: [
      ['Aslan', 'burç'], ['Kaplan', 'post'], ['Fil', 'hafıza'], ['Zürafa', 'benek'],
      ['Zebra', 'geçit'], ['Panda', 'bambu'], ['Kanguru', 'Migros'], ['Timsah', 'gözyaşı'],
      ['Penguen', 'belgesel'], ['Baykuş', 'Duolingo'], ['Kartal', 'semt'], ['Yunus', 'Emre'],
      ['Köpekbalığı', 'bebek'], ['Ahtapot', 'mürekkep'], ['Yılan', 'çıngırak'], ['Kaplumbağa', 'ninja'],
      ['Tavşan', 'Duracell'], ['Sincap', 'Alvin'], ['Kirpi', 'Sonic'], ['Yarasa', 'sonar'],
      ['Deve', 'kervan'], ['Su aygırı', 'nehir'], ['Gorilla', 'gökdelen'], ['Şempanze', 'taklit'],
      ['Kurt', 'dolunay'], ['Tilki', 'kümes'], ['Ayı', 'uyku'], ['Geyik', 'muhabbet'],
      ['Karınca', 'koloni'], ['Arı', 'Maya'],
    ],
  },
  {
    id: 'b_meyve_sebze',
    name: '🍎 Meyve & Sebze',
    words: [
      ['Elma', 'Newton'], ['Armut', 'piş'], ['Muz', 'Minyon'], ['Çilek', 'silgi'],
      ['Karpuz', 'çekirdek'], ['Kavun', 'koku'], ['Üzüm', 'bağ'], ['Portakal', 'Antalya'],
      ['Mandalina', 'kış'], ['Kiraz', 'küpe'], ['Vişne', 'likör'], ['Şeftali', 'emoji'],
      ['Kayısı', 'Malatya'], ['Nar', 'yılbaşı'], ['İncir', 'Aydın'], ['Kivi', 'Zelanda'],
      ['Ananas', 'pizza'], ['Avokado', 'tost'], ['Domates', 'İspanya'], ['Salatalık', 'kedi'],
      ['Patates', 'çuval'], ['Soğan', 'zam'], ['Havuç', 'motivasyon'], ['Biber', 'gaz'],
      ['Patlıcan', 'imam'], ['Kabak', 'tadı'], ['Ispanak', 'Popeye'], ['Marul', 'göbek'],
      ['Mısır', 'sinema'], ['Sarımsak', 'vampir'],
    ],
  },
  {
    id: 'b_ulkeler',
    name: '🌍 Ülkeler',
    words: [
      ['Türkiye', 'ayyıldız'], ['Almanya', 'gurbet'], ['Fransa', 'devrim'], ['İtalya', 'çizme'],
      ['İspanya', 'boğa'], ['İngiltere', 'Brexit'], ['Hollanda', 'lale'], ['Yunanistan', 'komşu'],
      ['Rusya', 'votka'], ['Çin', 'kopya'], ['Japonya', 'anime'], ['Güney Kore', 'BTS'],
      ['Hindistan', 'Bollywood'], ['Brezilya', 'samba'], ['Arjantin', 'pampa'], ['Meksika', 'kaktüs'],
      ['Kanada', 'akçaağaç'], ['Amerika', 'rüya'], ['Mısır', 'Nil'], ['Fas', 'Kazablanka'],
      ['Nijerya', 'prens'], ['Avustralya', 'ters'], ['İsveç', 'Nobel'], ['Norveç', 'fiyort'],
      ['Portekiz', 'Siuuu'], ['Polonya', 'Lehçe'], ['İsviçre', 'banka'], ['Belçika', 'waffle'],
    ],
  },
  {
    id: 'b_sehirler',
    name: '🏙️ Türkiye Şehirleri',
    words: [
      ['İstanbul', 'boğaz'], ['Ankara', 'memur'], ['İzmir', 'kordon'], ['Bursa', 'İskender'],
      ['Antalya', 'turist'], ['Adana', 'şalgam'], ['Konya', 'semazen'], ['Gaziantep', 'fıstık'],
      ['Trabzon', 'hamsi'], ['Samsun', 'Bandırma'], ['Eskişehir', 'çibörek'], ['Kayseri', 'pastırma'],
      ['Mersin', 'cezerye'], ['Diyarbakır', 'karpuz'], ['Erzurum', 'Palandöken'], ['Van', 'kahvaltı'],
      ['Muğla', 'Bodrum'], ['Aydın', 'efe'], ['Denizli', 'horoz'], ['Sakarya', 'Adapazarı'],
      ['Malatya', 'kayısı'], ['Rize', 'Ayder'], ['Sivas', 'kangal'], ['Çanakkale', 'geçilmez'],
      ['Balıkesir', 'Ayvalık'], ['Kocaeli', 'İzmit'], ['Şanlıurfa', 'çiğköfte'], ['Hatay', 'künefe'],
      ['Mardin', 'Mezopotamya'], ['Bolu', 'aşçı'],
    ],
  },
  {
    id: 'b_meslekler',
    name: '👔 Meslekler',
    words: [
      ['Doktor', 'yazı'], ['Öğretmen', 'tebeşir'], ['Mühendis', 'proje'], ['Avukat', 'cübbe'],
      ['Polis', 'kelepçe'], ['İtfaiyeci', 'hortum'], ['Aşçı', 'MasterChef'], ['Garson', 'bahşiş'],
      ['Berber', 'ense'], ['Terzi', 'mezura'], ['Marangoz', 'talaş'], ['Elektrikçi', 'sigorta'],
      ['Pilot', 'türbülans'], ['Hostes', 'anons'], ['Kaptan', 'dümen'], ['Şoför', 'dolmuş'],
      ['Hemşire', 'serum'], ['Eczacı', 'muadil'], ['Diş hekimi', 'dolgu'], ['Mimar', 'Sinan'],
      ['Ressam', 'palet'], ['Müzisyen', 'nota'], ['Oyuncu', 'motor'], ['Yazar', 'daktilo'],
      ['Gazeteci', 'manşet'], ['Çiftçi', 'efendi'], ['Balıkçı', 'olta'], ['Kasap', 'kıyma'],
      ['Fırıncı', 'hamur'], ['Veteriner', 'pati'],
    ],
  },
  {
    id: 'b_filmler',
    name: '🎬 Ünlü Filmler',
    words: [
      ['Titanik', 'buzdağı'], ['Avatar', 'Pandora'], ['Yüzüklerin Efendisi', 'kıymetlim'],
      ['Harry Potter', 'şimşek'], ['Yıldız Savaşları', 'kılıç'], ['Matrix', 'hap'],
      ['Jurassic Park', 'DNA'], ['Aslan Kral', 'hakuna'], ['Buz Devri', 'mamut'],
      ['Şrek', 'bataklık'], ['Karayip Korsanları', 'pusula'], ['Örümcek Adam', 'sorumluluk'],
      ['Batman', 'sinyal'], ['Süpermen', 'kripton'], ['İyi Kötü Çirkin', 'ıslık'],
      ['Esaretin Bedeli', 'IMDb'], ['Baba', 'teklif'], ['Forrest Gump', 'çikolata'],
      ['Interstellar', 'karadelik'], ['Başlangıç', 'topaç'], ['Joker', 'kahkaha'],
      ['Gladyatör', 'başparmak'], ['Terminatör', 'döneceğim'], ['Rocky', 'merdiven'],
      ['Rambo', 'bandana'],
    ],
  },
  {
    id: 'b_spor',
    name: '⚽ Spor Dalları',
    words: [
      ['Futbol', 'VAR'], ['Basketbol', 'smaç'], ['Voleybol', 'sultanlar'], ['Tenis', 'Wimbledon'],
      ['Yüzme', 'kulvar'], ['Boks', 'Ali'], ['Güreş', 'kispet'], ['Karate', 'kuşak'],
      ['Judo', 'kimono'], ['Tekvando', 'tekme'], ['Halter', 'Naim'], ['Atletizm', 'Bolt'],
      ['Bisiklet', 'Fransa'], ['Kayak', 'Uludağ'], ['Buz pateni', 'piruet'], ['Golf', 'delik'],
      ['Hokey', 'disk'], ['Beyzbol', 'sopa'], ['Rugby', 'oval'], ['Masa tenisi', 'Çin'],
      ['Badminton', 'tüy'], ['Okçuluk', 'Gazoz'], ['Eskrim', 'tuşe'], ['Binicilik', 'eyer'],
      ['Dalış', 'tüp'], ['Sörf', 'dalga'], ['Kürek', 'tekne'], ['Hentbol', 'kale'],
    ],
  },
  {
    id: 'b_ev_esya',
    name: '🛋️ Ev Eşyaları',
    words: [
      ['Koltuk', 'kumanda'], ['Masa', 'peçete'], ['Sandalye', 'kapmaca'], ['Yatak', 'pazartesi'],
      ['Dolap', 'çevirmek'], ['Buzdolabı', 'gece'], ['Fırın', 'kek'], ['Çamaşır makinesi', 'çorap'],
      ['Bulaşık makinesi', 'parlatıcı'], ['Televizyon', 'dantel'], ['Halı', 'saha'], ['Perde', 'tiyatro'],
      ['Ayna', 'kraliçe'], ['Lamba', 'cin'], ['Vantilatör', 'pervane'], ['Ütü', 'priz'],
      ['Süpürge', 'cadı'], ['Tencere', 'kapak'], ['Tava', 'krep'], ['Bardak', 'yarısı'],
      ['Tabak', 'porselen'], ['Çatal', 'yol'], ['Kaşık', 'elmas'], ['Bıçak', 'kemik'],
      ['Yastık', 'kavga'], ['Battaniye', 'dizi'], ['Saat', 'akrep'], ['Klima', 'ofis'],
    ],
  },
  {
    id: 'b_yiyecek',
    name: '🍔 Yiyecek & İçecek',
    words: [
      ['Pizza', 'makas'], ['Hamburger', 'menü'], ['Döner', 'Berlin'], ['Lahmacun', 'roka'],
      ['Pide', 'Ramazan'], ['Köfte', 'piyaz'], ['Kebap', 'mangal'], ['Mantı', 'yoğurt'],
      ['Börek', 'su'], ['Simit', 'vapur'], ['Baklava', 'şerbet'], ['Künefe', 'tel'],
      ['Dondurma', 'Maraş'], ['Çikolata', 'fondü'], ['Kek', 'kabarma'], ['Pasta', 'mum'],
      ['Makarna', 'öğrenci'], ['Pilav', 'fasulye'], ['Çorba', 'mercimek'], ['Salata', 'diyet'],
      ['Menemen', 'soğan'], ['Omlet', 'çırpma'], ['Çay', 'tavşankanı'], ['Kahve', 'hatır'],
      ['Ayran', 'köpük'], ['Limonata', 'nane'], ['Kola', 'Mentos'], ['Meyve suyu', 'pipet'],
    ],
  },
  {
    id: 'b_kahraman',
    name: '🦸 Süper Kahramanlar',
    words: [
      ['Örümcek Adam', 'tavan'], ['Demir Adam', '3000'], ['Kaptan Amerika', 'kalkan'], ['Thor', 'yıldırım'],
      ['Hulk', 'öfke'], ['Batman', 'mağara'], ['Süpermen', 'pelerin'], ['Wonder Woman', 'kement'],
      ['Flash', 'bellek'], ['Aquaman', 'Atlantis'], ['Kara Panter', 'Wakanda'], ['Doktor Strange', 'portal'],
      ['Ant-Man', 'küçülme'], ['Wolverine', 'Logan'], ['Deadpool', 'geveze'], ['Green Lantern', 'yüzük'],
      ['Yeşil Ok', 'kapüşon'], ['Kara Dul', 'ajan'], ['Şazam', 'uygulama'], ['Venom', 'dil'],
      ['Hawkeye', 'nişancı'], ['Vizyon', 'android'], ['Scarlet Witch', 'kaos'], ['Star-Lord', 'kasetçalar'],
    ],
  },
  {
    id: 'b_muzik',
    name: '🎸 Müzik & Çalgılar',
    words: [
      ['Gitar', 'akor'], ['Piyano', 'kuyruklu'], ['Keman', 'Stradivarius'], ['Davul', 'tokmak'],
      ['Flüt', 'çanta'], ['Trompet', 'boru'], ['Saksafon', 'caz'], ['Bağlama', 'tezene'],
      ['Ud', 'mızrap'], ['Kanun', 'madde'], ['Ney', 'sema'], ['Darbuka', 'ritim'],
      ['Zurna', 'düğün'], ['Klarnet', 'Hüsnü'], ['Akordeon', 'körük'], ['Arp', 'melek'],
      ['Çello', 'yaylı'], ['Kontrbas', 'dev'], ['Trombon', 'sürgü'], ['Org', 'kilise'],
      ['Mandolin', 'İtalyan'], ['Ksilofon', 'anaokulu'], ['Zil', 'teneffüs'], ['Tef', 'zilli'],
    ],
  },
  {
    id: 'b_diziler',
    name: '📺 Türk Dizileri',
    words: [
      ['Kurtlar Vadisi', 'cenaze'], ['Ezel', 'intikam'], ['Aşk-ı Memnu', 'yasak'],
      ['Muhteşem Yüzyıl', 'harem'], ['Diriliş Ertuğrul', 'oba'], ['Çukur', 'mahalle'],
      ['Leyla ile Mecnun', 'bakkal'], ['Avrupa Yakası', 'Burhan'], ['Çocuklar Duymasın', 'tiki'],
      ['Seksenler', 'nostalji'], ['Arka Sokaklar', 'ekip'], ['Kara Sevda', 'Emmy'],
      ['Kuruluş Osman', 'beylik'], ['Gibi', 'absürt'], ['Behzat Ç.', 'Ankara'],
      ['Yaprak Dökümü', 'Fikret'], ['Kuzey Güney', 'kardeş'], ['Fatmagül', 'suç'],
      ['Aşk Yeniden', 'uçak'], ['Yalı Çapkını', 'damat'],
    ],
  },
  {
    id: 'b_sarkicilar',
    name: '🎤 Şarkıcılar',
    words: [
      ['Tarkan', 'Şımarık'], ['Sezen Aksu', 'serçe'], ['Barış Manço', 'Gülpembe'],
      ['Ajda Pekkan', 'süperstar'], ['İbrahim Tatlıses', 'Urfa'], ['Müslüm Gürses', 'baba'],
      ['Zeki Müren', 'güneş'], ['Orhan Gencebay', 'batsın'], ['Neşet Ertaş', 'bozkır'],
      ['Cem Karaca', 'tamirci'], ['Ahmet Kaya', 'kum'], ['Sertab Erener', 'Eurovision'],
      ['MFÖ', 'üçlü'], ['Teoman', 'paramparça'], ['Sıla', 'hasret'], ['Mabel Matiz', 'masal'],
      ['Edis', 'Martılar'], ['Hadise', 'dümtektek'], ['Kenan Doğulu', 'şekerim'],
      ['Aleyna Tilki', 'Gesi'],
    ],
  },
  {
    id: 'b_oyunlar',
    name: '🎮 Video Oyunları',
    words: [
      ['Minecraft', 'küp'], ['Super Mario', 'tesisatçı'], ['Tetris', 'blok'], ['GTA', 'aranma'],
      ['PUBG', 'tavuk'], ['Fortnite', 'dans'], ['Among Us', 'mürettebat'], ['Candy Crush', 'davet'],
      ['Angry Birds', 'sapan'], ['Subway Surfers', 'tren'], ['Pac-Man', 'hayalet'], ['Yılan', 'Nokia'],
      ['FIFA', 'paket'], ['Counter-Strike', 'bomba'], ['League of Legends', 'toksik'],
      ['The Sims', 'havuz'], ['Zelda', 'prenses'], ['God of War', 'balta'],
      ['Red Dead', 'kovboy'], ['Witcher', 'canavar'],
    ],
  },
  {
    id: 'b_markalar',
    name: '🏷️ Markalar',
    words: [
      ['Nike', 'swoosh'], ['Adidas', 'çizgi'], ['Apple', 'ısırık'], ['Samsung', 'Galaxy'],
      ['Coca-Cola', 'Noel'], ['Pepsi', 'mavi'], ["McDonald's", 'palyaço'], ['Starbucks', 'isim'],
      ['Mercedes', 'yıldız'], ['Ferrari', 'at'], ['Lamborghini', 'traktör'], ['LEGO', 'tuğla'],
      ['IKEA', 'alyan'], ['Google', 'amca'], ['YouTube', 'abone'], ['Instagram', 'filtre'],
      ['Netflix', 'maraton'], ['Türk Hava Yolları', 'lokum'], ['Arçelik', 'robot'],
      ['Ülker', 'gofret'], ['BİM', 'aktüel'], ['Migros', 'kanguru'],
    ],
  },
  {
    id: 'b_vucut',
    name: '🖐️ Vücut Bölümleri',
    words: [
      ['Baş', 'tepe'], ['Saç', 'beyaz'], ['Göz', 'nazar'], ['Kulak', 'çınlama'],
      ['Burun', 'havada'], ['Ağız', 'birlik'], ['Dil', 'kemiksiz'], ['Diş', 'peri'],
      ['Boyun', 'borç'], ['Omuz', 'apolet'], ['Kol', 'saat'], ['Dirsek', 'temas'],
      ['El', 'emek'], ['Parmak', 'iz'], ['Tırnak', 'alıntı'], ['Göğüs', 'kafes'],
      ['Karın', 'guruldama'], ['Sırt', 'pehlivan'], ['Bel', 'kemer'], ['Bacak', 'kadar'],
      ['Diz', 'çökmek'], ['Ayak', 'uydurmak'], ['Topuk', 'Aşil'], ['Kaş', 'alma'],
      ['Kirpik', 'dilek'], ['Yanak', 'bayram'], ['Çene', 'düşük'], ['Alın', 'ter'],
    ],
  },
];
